spring:
  application:
    name: analyzer
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: deepseek-r1:7b
          temperature: 0.2

logging:
  level:
    com.campaign: DEBUG

server:
  port: 8090

api:
  base-url:
    campaign: https://ui-backendapi.mobavenue.com/api/reports/campaign/v2
    creative: https://ui-backendapi.mobavenue.com/api/reports/creative/v2
